use JSON to control all the data

diff --git a/src/loonmod.zsh.in b/src/loonmod.zsh.in
--- a/src/loonmod.zsh.in
+++ b/src/loonmod.zsh.in
@@ -1,7 +1,7 @@
 #!/usr/bin/env zsh
 
 export LOONCONFIG=@CMAKE_LOONLOCAL_CACHE@
-MOD_SEQ=
+MOD_SEQ="{}"
 
 function mod_db()
 {
@@ -17,12 +17,14 @@ function listarray()
 
 function export_all()
 {
-    export PATH=`grep -A 1 "^PATH=" <<< $1 | tail -n 1`
-    export C_INCLUDE_PATH=`grep -A 1 "^C_INCLUDE_PATH=" <<< $1 | tail -n 1`
-    export CPLUS_INCLUDE_PATH=`grep -A 1 "^CPLUS_INCLUDE_PATH=" <<< $1 | tail -n 1`
-    export LIBRARY_PATH=`grep -A 1 "^LIBRARY_PATH=" <<< $1 | tail -n 1`
-    export LD_LIBRARY_PATH=`grep -A 1 "^LD_LIBRARY_PATH=" <<< $1 | tail -n 1`
-    export DYLD_LIBRARY_PATH=`grep -A 1 "^DYLD_LIBRARY_PATH=" <<< $1 | tail -n 1`
+    mod_func_script=@CMAKE_INSTALL_PREFIX@/bin/mod_func.py
+
+    export DYLD_LIBRARY_PATH=`python2 ${mod_func_script} parsereturn "$1" dyld_library_path`
+    export LD_LIBRARY_PATH=`python2 ${mod_func_script} parsereturn "$1" ld_library_path`
+    export LIBRARY_PATH=`python2 ${mod_func_script} parsereturn "$1" library_path`
+    export CPLUS_INCLUDE_PATH=`python2 ${mod_func_script} parsereturn "$1" cplus_include_path`
+    export C_INCLUDE_PATH=`python2 ${mod_func_script} parsereturn "$1" c_include_path`
+    export PATH=`python2 ${mod_func_script} parsereturn "$1" path`
 }
 
 function print_loonmod_usage()
@@ -64,10 +66,10 @@ function loonmod()
 
     elif [[ "$subcmd" == "clear" ]]; then
         retstr=`python2 ${mod_func_script} clear --seq "${MOD_SEQ}"`
-        if [[ "${retstr}" != "END" ]]; then
-            MOD_SEQ=""
-            export_all ${retstr}
+        if [[ "${retstr}" != "{}" ]]; then
+            export_all "${retstr}"
         fi
+        MOD_SEQ="{}"
 
     elif [[ "$subcmd" == "depend" ]]; then
         listarray `python2 ${mod_func_script} depend -n $@`
@@ -80,26 +82,37 @@ function loonmod()
 
     elif [[ "$subcmd" == "load" ]]; then
         retstr=`python2 ${mod_func_script} load --seq "${MOD_SEQ}" -n $@`
-        if [[ "${retstr}" == "LOADED" ]]; then
+        retval=`python2 ${mod_func_script} parsereturn "${retstr}" retval`
+        if [[ "${retval}" == "LOADED" ]]; then
             echo "Module [$@] has already been loaded" >&2
-        elif [[ "${retstr}" == "WRONG_NAME" ]]; then
+
+        elif [[ "${retval}" == "UPGRADED" ]]; then
+            MOD_SEQ=`python2 ${mod_func_script} parsereturn "${retstr}" seq`
+            echo "Module [$@] has now been upgraded to 'U' type" >&2
+        
+        elif [[ "${retval}" == "UNKNOWN_TYPE" ]]; then
+            echo "[ERROR]: Module [$@] has a wrong type. Something went wrong!!!" >&2
+
+        elif [[ "${retval}" == "WRONG_NAME" ]]; then
             echo "[ERROR]: No module named [$@]" >&2
+
+        elif [[ "${retval}" == "GOOD" ]]; then
+            MOD_SEQ=`python2 ${mod_func_script} parsereturn "${retstr}" seq`
+            export_all "${retstr}"
         else
-            MOD_SEQ=`grep -A 1 "^MOD_SEQ=" <<< ${retstr} | tail -n 1`
-            export_all ${retstr}
-            dep=`echo ${retstr} | tail -n +16`
-            if [[ "$dep" != "END" ]]; then
-                echo "Unloaded dependencies:" >&2
-                listarray ${dep}
-            fi
+            echo "[ERROR]: Unknown return value [${retval}]!!!"
         fi
 
     elif [[ "$subcmd" == "unload" ]]; then
         retstr=`python2 ${mod_func_script} unload --seq "${MOD_SEQ}" -n $@`
-        if [[ "${retstr}" == "NOT_LOADED" ]]; then
+        retval=`python2 ${mod_func_script} parsereturn "${retstr}" retval`
+        if [[ "${retval}" == "NOT_LOADED" ]]; then
             echo "Module [$@] was not loaded" >&2
-        elif [[ "${retstr}" != "END" ]]; then
-            MOD_SEQ=`grep -A 1 "^MOD_SEQ=" <<< ${retstr} | tail -n 1`
+        else
+            if [[ "${retval}" == "SHOW_WARNING" ]]; then
+                echo "[WARNING]: Module [$@] has been unloaded successfully, but some modules depend on it" >&2
+            fi
+            MOD_SEQ=`python ${mod_func_script} parsereturn "${retstr}" seq`
             export_all ${retstr}
         fi
 
